### ISSUE TITLE
Index Type Typo

### ISSUE THREAD

**Issue by pshea76** [MarineRoboticsGroup/dcsam#4]
Looks like you accidentally cast your index to double:
https://github.com/MarineRoboticsGroup/dcsam/blob/main/include/dcsam/DCMaxMixtureFactor.h#L120
https://github.com/MarineRoboticsGroup/dcsam/blob/main/include/dcsam/DCMaxMixtureFactor.h#L127
https://github.com/MarineRoboticsGroup/dcsam/blob/main/include/dcsam/DCMaxMixtureFactor.h#L135

Assuming that's not on purpose?

Cheers,
Pat

**Comment by keevindoherty** [comment]
Good catch! Thanks Pat!

cc: @kurransingh
